spring:
  application:
    name: lib-custom-dto
  kafka:
    bootstrap-servers: ${URL_KAFKA:kafka:9092}
    security:
      protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: uteam-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring:
          json:
            trusted:
              packages: *
    consumers:
      - ru.fvds.cdss13.lib.dto.ad.AdDto
      - ru.fvds.cdss13.lib.dto.ad.AdFilterDto
      - ru.fvds.cdss13.lib.dto.ad.RequestAdsAllDto_AdDto
      - ru.fvds.cdss13.lib.dto.ad.RequestCityAllDto_CityDto
      - ru.fvds.cdss13.lib.dto.ad.RequestTagAllDto_TagDto
      - ru.fvds.cdss13.lib.dto.project.ProjectDto_Ads
      - ru.fvds.cdss13.lib.dto.tag.TagDto

