name: Publish to GitHub Packages

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Publish
        env:
          GPR_USER: ${{ secrets.GPR_USERNAME }}
          GPR_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
        run: |
          ./gradlew publish \
            -Pgpr.user=$GPR_USER \
            -Pgpr.key=$GPR_TOKEN \
            --stacktrace